version: "2"
run:
  build-tags:
    - netgo
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    # - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 30
      statements: 20
    gocognit:
      min-complexity: 9
    gocyclo:
      min-complexity: 7
    govet:
      disable:
        - fieldalignment
      enable-all: true
      disable-all: false
    lll:
      line-length: 120
    misspell:
      locale: UK
    nakedret:
      max-func-lines: 20
    nestif:
      min-complexity: 2
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    whitespace:
      multi-if: true
      multi-func: false
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - err
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - cyclop
          - funlen
          - gocognit
          - gocyclo
          - maintidx
          - revive
        path: _test\.go
      - linters:
          - funlen
          - mnd
        path: internal
      - linters:
          - dupl
          - forbidigo
          - gochecknoglobals
          - gochecknoinits
        path: cmd
      - linters:
          - forbidigo
        path: version\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: master
formatters:
  enable:
    - gci
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ch/from\.go
